[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
ciborium = "0.2.2"
derive = "1.0.0"
ecdsa = { version = "0.17.0", features = ["sha2", "serde", "pem"] }
k256 = { version = "0.14.0", features = ["serde", "pem", "ecdsa"] }
serde = { version = "1.0.229", features = ["derive"] }
sha256 = "1.6.0"
uint = "0.10.1"
uuid = {version = "1.26.1" , features=["v4" , "serde"]}
